FROM python:3.11-slim

WORKDIR /app

# copier les dépendances API
COPY api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copier le code API
COPY api /app/api

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
