FROM python:3.10-slim

WORKDIR /app

# Copier les dépendances API
COPY api/requirements.txt .

# Mettre pip à jour + installer avec timeout plus long et retries
RUN pip install --upgrade pip && \
    pip install --default-timeout=100 --retries=5 --no-cache-dir -r requirements.txt

# Copier le code API
COPY api /app/api

EXPOSE 8000

# Commande pour lancer FastAPI
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
